### ISSUE TITLE
Multiple Errors

### ISSUE THREAD

**Issue by Merlin04** [shoumikhin/StreamScanner#1]
I get many errors when I run the command "swift StreamScanner.swift":
StreamScanner.swift:46:44: error: cannot convert value of type 'NSString' to type 'String' in coercion
                buffer = NSScanner(string: nextInput as String)
                                           ^~~~~~~~~
StreamScanner.swift:60:49: error: extra argument 'intoString' in call
            if buffer!.scanUpToCharactersFromSet(delimiters, intoString: &token) && token != nil
                                                ^                        ~~~~~~
StreamScanner.swift:63:46: error: extra argument 'intoString' in call
                buffer!.scanCharactersFromSet(delimiters, intoString: nil)
                                             ^                        ~~~
StreamScanner.swift:66:38: warning: cast from 'NSString?' to unrelated type 'String' always fails
                return convert(token as! String)
                               ~~~~~ ^   ~~~~~~

**Comment by shoumikhin** [comment]
What version of Swift do you use? What are you trying to accomplish?

**Comment by Merlin04** [comment]
When I type "swift" at the command line, I see this:
Welcome to Swift version 2.2-dev (LLVM 46be9ff861, Clang 4deb154edc, Swift 778f82939c). Type :help for assistance.
  1>  

I am trying to get user input for this script:
func veggiePineapple(vegetable:String) -> String {
switch vegetable {
case "celery":
    return "Add some raisins and make ants on a log."
case "cucumber", "watercress":
    return "That would make a good tea sandwich."
case "pepper", "spicy":
    return "Is it spicy?"
default:
    return "Everything tastes good in soup."
}
}

print(veggiePineapple(The_Input_From_StreamScanner))

**Comment by shoumikhin** [comment]
Try using Swift 2.1.1 which comes with Xcode 7.2, released yesterday.

Then to compile your program with command line run:
swiftc <path_to>/StreamScanner/StreamScanner.swift <your_program_name>.swift

Or just create a new Xcode project and copy StreamScanner.swift to it.
Then you'll be able to import StreamScanner and use it just as it's used in the test app (StreamScannerTest/main.swift).

**Comment by Merlin04** [comment]
I don't use Xcode. I am on Ubuntu.

**Comment by shoumikhin** [comment]
That is the key.
Then install Swift 2.1.1and try again.
