### ISSUE TITLE
Protocol conformance

### ISSUE THREAD

**Issue by Tiza59** [shoumikhin/StreamScanner#3]
Please can you fix the error "type 'StreamScanner' does not conform to protocol 'Sequence' ?
I have cloned your project and opened it under XCode 9.2: I could neither compile it under Swift 3.2. or Swift 4.

Thanks in advance, kind regards
Uwe

**Comment by rth238** [comment]
This looks to be a very useful!  However, as Tiza50 has indicated, there is an error with v 4.  I'm not familiar enough with Swift to fix on my own...

Thanks, in advance, if this can be updated to address the issue... Rich

**Comment by theangelperalta** [comment]
@Tiza59, @rth238 I have created a Pull Request that is a fix for this issue. If not merged, please checkout my fork of this repo that includes the fix for this issue: [link](https://www.github.com/acort3255/StreamScanner)

**Comment by shoumikhin** [comment]
@acort3255 that’s awesome, thank you!

**Comment by theangelperalta** [comment]
>@acort3255 that’s awesome, thank you!

@shoumikhin Yeah, no problem. Thanks for this awesome repo!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
